layoutdir = "themes/hugo-academic-group/layouts"
publishdir = "public"
static = "static"
builddrafts = true
# Replace this with your website URL
baseurl = "https://balazslab.netlify.com/"
canonifyurls = true
theme = "hugo-academic-group"
title = "Balazs Lab"
math = true
copyright = "&copy; Balazs Lab, 2018 "

[taxonomies]
category = "categories"
tag = "tags"


[params]
  description = "Website of research group"
  author = "Team Members of Balazs Lab"
  email = "balazs@pitt.edu"
  address = "4420 Bayard St, Pittsburgh, PA 15213"

  slogan = "BALAZS LAB"
  slogan_text = "Soft Condensed Matter: Theory & Simulations"

#  [[params.slogan_columns]]
#    title = "About"
#    text =  ""
#    link = "/about"
#    link_text = "Meet the team"
#    weight = 1
#
#  [[params.slogan_columns]]
#    title = "Mission"
#    text = ""
#    link = "/mission"
#    link_text = "Read more"
#    weight = 2
#
#  [[params.slogan_columns]]
#    title = "Approach"
#    text = ""
#    link = "/approach"
#    link_text = "Read more"
#    weight = 3

  # Selected Publications section.
  [params.publications_selected]
    detailed_list = true
    title = "Selected Publications"
    subtitle = ""

  # Publications section.
  # Section will only be displayed if there are publications in `content/publication/`.
  [params.publications]
    count = 5
    detailed_list = false
    title = "Publications"
    subtitle = ""
    str_all = "More Publications"


  # Research section.
  # Section will only be displayed if there are research in `content/project/`.
  [params.research]
    title = "Research"
    subtitle = ""
    count = 2
    str_all = "More on Research"
    str_read_more = "Read More"

  # Vacancies section
  # Section will only be displayed if there are valid vacancies in `content/vacancy`
  [params.vacancies]
    title = "Vacancies"
    subtitle = ""
    count = 3
    str_all = "More Vacancies"
    str_read_more = "Read More"

  # Contact section.
  [params.contact]
    enable = true
    title = "Contact"
    subtitle = ""
    autolink = false  # Automatically link email and phone?

  # Navigation Links
  #   The weight parameter defines the order that the links will appear in.

  [[menu.main]]
      name = "Home"
      url = "#top"
      weight = 1

  [[menu.main]]
        name = "Research"
        url = "#research"
        weight = 2

  [[menu.main]]
      name = "Publications"
      url = "#publications"
      weight = 3

  [[menu.main]]
      name = "Members"
      url = "#members"
      weight = 4

  [[menu.main]]
      name = "Contact"
      url = "#contact"
      weight = 5
